-- Quartermaster v1; apply to a new, dedicated Supabase project.
begin;
create extension if not exists pgcrypto;
create table public.users (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', username text unique, avatar_url text, preferences jsonb not null default '{}'::jsonb check (jsonb_typeof(preferences)='object'), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.games (id uuid primary key default gen_random_uuid(), slug text not null unique, name text not null, publisher text, cover_image_url text, icon_url text, game_type text, definition jsonb not null default '{}'::jsonb check (jsonb_typeof(definition)='object'), active boolean not null default true, created_at timestamptz not null default now());
create table public.user_games (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, game_id uuid not null references public.games(id), platform text not null, store text not null default '', account_name text not null default '', server text not null default '', status text not null default 'active' check(status in ('active','paused','retired')), last_played_at timestamptz, custom_data jsonb not null default '{}'::jsonb check(jsonb_typeof(custom_data)='object'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id), unique(user_id,game_id,platform,store,account_name,server));
create table public.characters (id uuid primary key default gen_random_uuid(), user_id uuid not null, user_game_id uuid not null, name text not null, level numeric(12,2) check(level>=0), class_name text, subclass text, race text, gear_score numeric(16,2) check(gear_score>=0), status text not null default 'active' check(status in ('active','alt','retired')), portrait_url text, custom_data jsonb not null default '{}'::jsonb check(jsonb_typeof(custom_data)='object'), last_synced_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id), unique(id,user_id,user_game_id), foreign key(user_game_id,user_id) references public.user_games(id,user_id) on delete cascade);
create table public.builds (id uuid primary key default gen_random_uuid(), user_id uuid not null, character_id uuid not null, name text not null, purpose text, is_active boolean not null default false, description text, custom_data jsonb not null default '{}'::jsonb check(jsonb_typeof(custom_data)='object'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id,character_id), unique(id,user_id), foreign key(character_id,user_id) references public.characters(id,user_id) on delete cascade);
create unique index builds_one_active_per_character on public.builds(character_id) where is_active;
create table public.equipment (id uuid primary key default gen_random_uuid(), user_id uuid not null, character_id uuid not null, name text not null, slot text, rarity text, item_level numeric(16,2) check(item_level>=0), upgrade_rank integer check(upgrade_rank>=0), quantity integer not null default 1 check(quantity>0), locked boolean not null default false, custom_data jsonb not null default '{}'::jsonb check(jsonb_typeof(custom_data)='object'), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id,character_id), unique(id,user_id), foreign key(character_id,user_id) references public.characters(id,user_id) on delete cascade);
create table public.build_equipment (id uuid primary key default gen_random_uuid(), user_id uuid not null, character_id uuid not null, build_id uuid not null, equipment_id uuid not null, slot text not null, slot_position integer not null default 1 check(slot_position>0), created_at timestamptz not null default now(), unique(build_id,slot,slot_position), foreign key(build_id,user_id,character_id) references public.builds(id,user_id,character_id) on delete cascade, foreign key(equipment_id,user_id,character_id) references public.equipment(id,user_id,character_id) on delete cascade);
create table public.progression (id uuid primary key default gen_random_uuid(), user_id uuid not null, user_game_id uuid not null, character_id uuid, key text not null, label text not null, numeric_value numeric(20,4), text_value text, max_value numeric(20,4), custom_data jsonb not null default '{}'::jsonb check(jsonb_typeof(custom_data)='object'), recorded_at timestamptz not null default now(), foreign key(user_game_id,user_id) references public.user_games(id,user_id) on delete cascade, foreign key(character_id,user_id,user_game_id) references public.characters(id,user_id,user_game_id) on delete cascade);
create unique index progression_account_key on public.progression(user_game_id,key) where character_id is null;
create unique index progression_character_key on public.progression(character_id,key) where character_id is not null;
create table public.stats (id uuid primary key default gen_random_uuid(), user_id uuid not null, character_id uuid not null, build_id uuid, key text not null, label text not null, numeric_value numeric(20,4), text_value text, unit text, recorded_at timestamptz not null default now(), foreign key(character_id,user_id) references public.characters(id,user_id) on delete cascade, foreign key(build_id,user_id,character_id) references public.builds(id,user_id,character_id) on delete cascade);
create unique index stats_character_key on public.stats(character_id,key) where build_id is null;
create unique index stats_build_key on public.stats(build_id,key) where build_id is not null;
create table public.goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, user_game_id uuid, character_id uuid, title text not null, description text, next_action text, goal_type text, priority text not null default 'medium' check(priority in ('low','medium','high')), status text not null default 'open' check(status in ('open','in_progress','done','paused')), target_value numeric(20,4), current_value numeric(20,4), target_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,user_id), check(character_id is null or user_game_id is not null), foreign key(user_game_id,user_id) references public.user_games(id,user_id) on delete cascade, foreign key(character_id,user_id,user_game_id) references public.characters(id,user_id,user_game_id) on delete cascade);
create table public.notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, game_id uuid references public.games(id), user_game_id uuid, character_id uuid, build_id uuid, equipment_id uuid, goal_id uuid, body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(num_nonnulls(game_id,user_game_id,character_id,build_id,equipment_id,goal_id)=1), foreign key(user_game_id,user_id) references public.user_games(id,user_id) on delete cascade, foreign key(character_id,user_id) references public.characters(id,user_id) on delete cascade, foreign key(build_id,user_id) references public.builds(id,user_id) on delete cascade, foreign key(equipment_id,user_id) references public.equipment(id,user_id) on delete cascade, foreign key(goal_id,user_id) references public.goals(id,user_id) on delete cascade);
create table public.snapshots (id uuid primary key default gen_random_uuid(), user_id uuid not null, character_id uuid not null, source text not null default 'manual', payload jsonb not null check(jsonb_typeof(payload)='object'), captured_at timestamptz not null default now(), foreign key(character_id,user_id) references public.characters(id,user_id) on delete cascade);
create index on public.user_games(user_id,game_id);
create index on public.characters(user_game_id);
create index on public.builds(character_id);
create index on public.equipment(character_id);
create index on public.build_equipment(user_id,character_id);
create index on public.progression(user_id,user_game_id);
create index on public.stats(user_id,character_id);
create index on public.goals(user_id,status);
create index on public.notes(user_id,created_at desc);
create index on public.snapshots(character_id,captured_at desc);
-- Every user-owned row carries user_id; composite foreign keys prevent cross-account references.
do $$ declare t text; begin foreach t in array array['users','games','user_games','characters','builds','equipment','build_equipment','progression','stats','goals','notes','snapshots'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy games_read on public.games for select to authenticated using (active);
-- Catalog mutations are performed by privileged migrations only.
do $$ declare t text; begin foreach t in array array['user_games','characters','builds','equipment','build_equipment','progression','stats','goals','notes','snapshots'] loop
 execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid()) = %I)',t||'_select',t,'user_id');
 execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid()) = %I)',t||'_insert',t,'user_id');
 execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid()) = %I) with check ((select auth.uid()) = %I)',t||'_update',t,'user_id','user_id');
 execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid()) = %I)',t||'_delete',t,'user_id');
 end loop; end $$;
-- The profile key itself is the Auth user ID.
create policy users_select on public.users for select to authenticated using ((select auth.uid())=id);
create policy users_insert on public.users for insert to authenticated with check ((select auth.uid())=id);
create policy users_update on public.users for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create policy users_delete on public.users for delete to authenticated using ((select auth.uid())=id);
revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select on public.games to authenticated;
grant select,insert,update,delete on public.users,public.user_games,public.characters,public.builds,public.equipment,public.build_equipment,public.progression,public.stats,public.goals,public.notes,public.snapshots to authenticated;
commit;
